### ISSUE TITLE
微信读书问题

### ISSUE THREAD

**Issue by HongJunShan** [zhuxiaojian/config#1]
你好，请问下https://weread.nanwang.de页面除了用了weread2notion还用了其他仓库的代码了吗，非常漂亮，打开就是页面而不是notion那个想问下怎么做的？

**Comment by zhuxiaojian** [comment]
只是使用了 weread2notion 获取数据到 Notion，然后自己写了一套服务和页面去接 [Notions Public API](https://developers.notion.com/)，这就比较定制化了

**Comment by HongJunShan** [comment]
收到，谢谢👍
